<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypeshell="application/xml"?>
<package format="3">
  <name>base</name>
  <version>0.0.1</version>
  <description>Base chassis driver node</description>
  <maintainer email="you@example.com">Richard Zang</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>serial</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
